Resources:
  AppNode: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0080e4c5bc078760e
      KeyName: aws-keys
      SecurityGroups:
        - !Ref AppNodeSG
      UserData: !Base64 |
        #!/bin/bash
        sudo su
        yum update -y
        yum install docker -y
        # usermod -a -G docker ${USER}
        service docker start
        curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
        yum install git -y
        # usermod -a -G git ${USER}
        git clone https://github.com/feysalh/webpage.git  ~/webpage
        (cd ~/webpage && docker-compose up -d)
    
  AppNodeVM:      
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-east-1c
      Size: 8
      VolumeType: gp2
    
  AppNodeSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: for our apps to access via docker
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '4000'
        ToPort: '4000'
        CidrIp: 0.0.0.0/0
  
  
